# /etc/kubernetes/eventratelimit-server-namespace-user.yaml
---
apiVersion: eventratelimit.admission.k8s.io/v1alpha1
kind: Configuration
limits:
  - type: Server
    qps: 100
    burst: 200
  - type: Namespace
    qps: 25
    burst: 50
    cacheSize: 4096
  - type: User
    qps: 10
    burst: 15
...