---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-servicemonitors
  namespace: rook-ceph
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    spec:
      serviceAccountName: sm-patcher
      containers:
        - name: patch-servicemonitor
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              kubectl patch servicemonitor rook-ceph-exporter -n rook-ceph --type='merge' -p '{"metadata":{"labels":{"release":"kube-prometheus"}}}'
              kubectl patch servicemonitor rook-ceph-mgr -n rook-ceph --type='merge' -p '{"metadata":{"labels":{"release":"kube-prometheus"}}}'
      restartPolicy: Never
...