# /etc/kubernetes/enc/encryption-config.yaml
---
kind: EncryptionConfiguration
apiVersion: apiserver.config.k8s.io/v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: <key1-value>
      - identity: {}
...