# helm-kube-prome-stack-override-values.yaml
#
---
kubeTargetVersionOverride: 1.32.1

kubeEtcd:
  service:
    enabled: false
  serviceMonitor:
    scheme: https
    insecureSkipVerify: true
    port: https
    selector:
      matchLabels:
        app: kube-rbac-proxy-etcd
...