---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: calico-kube-controllers-metrics-monitor
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
  namespaceSelector:
    matchNames:
      - calico-system
  endpoints:
    - port: metrics-port
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
...